// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[...]').default>>>>
    }
    '/api/ai/models': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/models.get').default>>>>
    }
    '/api/ai/quizzes': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/quizzes.post').default>>>>
    }
    '/api/health': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health').default>>>>
    }
    '/api/proxy': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy').default>>>>
    }
    '/api/webhooks/test': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/test.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-site-config/dist/runtime/nitro/routes/__site-config__/debug').default>>>>
    }
    '/__sitemap__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/__sitemap__/debug').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xml').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}