// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/20/2025, 5:29:24 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/aniasse/Me/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/aniasse/Me/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/aniasse/Me/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/aniasse/Me/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/aniasse/Me/portfolio/plugins/**/*.{js,ts,mjs}","/home/aniasse/Me/portfolio/composables/**/*.{js,ts,mjs}","/home/aniasse/Me/portfolio/utils/**/*.{js,ts,mjs}","/home/aniasse/Me/portfolio/pages/about.vue","/home/aniasse/Me/portfolio/pages/index.vue","/home/aniasse/Me/portfolio/pages/contact.vue","/home/aniasse/Me/portfolio/pages/projects.vue","/home/aniasse/Me/portfolio/pages/[...slug].vue","/home/aniasse/Me/portfolio/pages/blog/rust.vue","/home/aniasse/Me/portfolio/pages/blog/index.vue","/home/aniasse/Me/portfolio/pages/blog/devops.vue","/home/aniasse/Me/portfolio/pages/technologies.vue","/home/aniasse/Me/portfolio/pages/blog/security.vue","/home/aniasse/Me/portfolio/pages/docs/doc-base.vue","/home/aniasse/Me/portfolio/pages/blog/authentication.vue","/home/aniasse/Me/portfolio/pages/docs/vue-drag-scroller.vue","/home/aniasse/Me/portfolio/pages/docs/superbad-ecommerce.vue","/home/aniasse/Me/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/aniasse/Me/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/aniasse/Me/portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;